language: node_js

node_js:
  - node # latest stable Node.js release

branches:
  only:
    - master # 只检测 master 分支上的 commit

intall:
  - yarn install

script:
  - yarn run build

after_success:
  - git config --global user.name "sqrtthree"
  - git config --global user.email "imsqrtthree@gmail.com"
  - GH_TOKEN=$GH_TOKEN yarn run deploy
